name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v6
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check GitHub OIDC token
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Job: $GITHUB_JOB"
          echo "OIDC token URL exists: ${ACTIONS_ID_TOKEN_REQUEST_URL:+yes}"
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491144990032:role/GitHubActions-ECR-Role
          aws-region: ap-south-1
      - name: Build docker Image
        run: docker build -t myapp:v1 .
      - name: docker image
        run: docker images


