name: CI

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v6

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check OIDC Claims
        run: |
          TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | python -c "import sys,json; print(json.load(sys.stdin)['value'])")

          export OIDC_TOKEN="$TOKEN"

          python - <<'PY'
          import os
          import json
          import base64

          token = os.environ["OIDC_TOKEN"]
          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(
              base64.urlsafe_b64decode(payload)
          )

          print("OIDC issuer:", claims.get("iss"))
          print("OIDC audience:", claims.get("aud"))
          print("OIDC subject:", claims.get("sub"))
          PY

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491144990032:role/GitHubActions-ECR-Role
          aws-region: ap-south-1

      - name: Build docker Image
        run: docker build -t myapp:v1 .

      - name: docker image
        run: docker images